version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: vexpenses_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: vexpenses_db
      MYSQL_USER: vexpenses_user
      MYSQL_PASSWORD: vexpenses_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql-db-data:/var/lib/mysql
    networks:
      - vexpenses
    command:
      --max_connections=1000
      --wait_timeout=300
      --interactive_timeout=300

  redis:
    image: redis:alpine
    container_name: vexpenses_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - vexpenses
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_vexpenses
    volumes:
      - .:/app/api_vexpenses
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - APP_NAME=Vexpenses
      - APP_ENV=local
      - APP_KEY=base64:unu3yNArF5S+3p7uO5crF5GWL/jZ8hBg4Rr/C6BW19Q=
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000

      - APP_LOCALE=en
      - APP_FALLBACK_LOCALE=en
      - APP_FAKER_LOCALE=en_US

      - APP_MAINTENANCE_DRIVER=file

      - PHP_CLI_SERVER_WORKERS=4

      - BCRYPT_ROUNDS=12

      - LOG_CHANNEL=stack
      - LOG_STACK=single
      - LOG_DEPRECATIONS_CHANNEL=null
      - LOG_LEVEL=debug

      - DB_CONNECTION=mysql
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_DATABASE=vexpenses_db
      - DB_USERNAME=vexpenses_user
      - DB_PASSWORD=vexpenses_pass

      - SESSION_DRIVER=redis
      - SESSION_LIFETIME=120
      - SESSION_ENCRYPT=false
      - SESSION_PATH=/
      - SESSION_DOMAIN=null

      - BROADCAST_CONNECTION=log
      - FILESYSTEM_DISK=local
      - QUEUE_CONNECTION=redis

      - CACHE_STORE=redis

      - MEMCACHED_HOST=127.0.0.1

      - REDIS_CLIENT=phpredis
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379

      - MAIL_NOT_REPLY=smtp
      - MAIL_SCHEME=null
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_ENCRYPTION=null
      - MAIL_USERNAME="alysontrizotto1@gmail.com"
      - MAIL_PASSWORD="hsgriypfkbkwhony"
      - MAIL_FROM_ADDRESS="${MAIL_USERNAME}"
      - MAIL_FROM_NAME="${APP_NAME}"

      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_BUCKET=
      - AWS_USE_PATH_STYLE_ENDPOINT=false

      - VITE_APP_NAME="${APP_NAME}"
    depends_on:
      - mysql-db
      - redis
    networks:
      - vexpenses
    ports:
      - "8030:8030"
    entrypoint: ./scripts/entrypoint.sh

volumes:
  mysql-db-data:
  caddy_data:
  caddy_config:
  redis-data:

networks:
  vexpenses:
    external: true
    driver: bridge
