version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: vexpenses_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: vexpenses_db
      MYSQL_USER: vexpenses_user
      MYSQL_PASSWORD: vexpenses_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql-db-data:/var/lib/mysql
    networks:
      - vexpenses

  redis:
    image: redis:alpine
    container_name: vexpenses_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - vexpenses
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_vexpenses
    volumes:
      - .:/app/api_vexpenses
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_DATABASE=vexpenses_db
      - DB_USERNAME=vexpenses_user
      - DB_PASSWORD=vexpenses_pass
    depends_on:
      - mysql-db
      - redis
    networks:
      - vexpenses
    ports:
      - "8030:8030"
    entrypoint: ./scripts/entrypoint.sh

volumes:
  mysql-db-data:
  caddy_data:
  caddy_config:
  redis-data:

networks:
  vexpenses:
    external: true
    driver: bridge
